name: Build mempool-rebroadcaster CI
permissions:
    contents: read

on:
    workflow_dispatch:

env:
    CARGO_TERM_COLOR: always

jobs:
    docker-build:
        name: Build docker
        runs-on: ubuntu-latest
        steps:
            - name: Harden the runner (Audit all outbound calls)
              uses: step-security/harden-runner@002fdce3c6a235733a90a27c80493a3241e56863 # v2.12.1
              with:
                  egress-policy: audit

            - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
            - name: Set up QEMU
              uses: docker/setup-qemu-action@49b3bc8e6bdd4a60e6116a5414239cba5943d3cf # v3.2.0
            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@e468171a9de216ec08956ac3ada2f0791b6bd435 # v3.11.1
            - name: Login to DockerHub
              id: login-action
              uses: docker/login-action@v3
              with:
                  username: ${{ secrets.DOCKERHUB_USERNAME }}
                  password: ${{ secrets.DOCKERHUB_TOKEN }}
            - name: Build and push
              id: docker_build
              uses: docker/build-push-action@v5
              with:
                  context: .
                  file: ./dockerfile.pool
                  platforms: linux/amd64, linux/arm64
                  push: true
                  tags: xlayerdev/mempool-rebroadcaster:latest
